<a href="https://colab.research.google.com/github/shoxruxmamitov/fayllar-va-malumotlar-ombor/blob/main/guruhlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd #pandas kutubxonasini chaqirib oldii

In [ ]:
import numpy as np # np kutubxonasini chaqirib oldik

In [ ]:
tr = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population.csv', usecols=['country', 'pop2021', 'area'], index_col='country')
# jadvalni dataframe korinishiga otkizdik  va count, pop2021, area ustunlarini usecols orqali chaqirib oldik

.cut() va .qcut()

In [ ]:
tr.head() # 5 qatorni chiqarib oldik

            pop2021  area
country
Macau       658.394    30
Monaco       39.511     2
Singapore  5896.686   710
Hong Kong  7552.810  1104
Gibraltar    33.698     6

In [ ]:
tr.loc['India'] # india malumotlarini chaqirib oldik

pop2021    1393409.038
area       3287590.000
Name: India, dtype: float64

In [ ]:
tr.loc['Uzbekistan'] # uzbekistan malumotlarini chaqirib oldik

pop2021     33935.763
area       447400.000
Name: Uzbekistan, dtype: float64

In [ ]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]
# list korinishida sonlarni hosil qildik

In [ ]:
popilation = tr.pop2021

In [ ]:
guruh = pd.cut(popilation, bins)
guruh # guruhlarga bolib oldik oraliqlarni bilib oldish uchun ishlatdik

country
Macau                   (0, 1000]
Monaco                  (0, 1000]
Singapore           (1000, 10000]
Hong Kong           (1000, 10000]
Gibraltar               (0, 1000]
                        ...
Namibia             (1000, 10000]
Western Sahara          (0, 1000]
Mongolia            (1000, 10000]
Falkland Islands        (0, 1000]
Greenland               (0, 1000]
Name: pop2021, Length: 232, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

In [ ]:
guruh.value_counts()
# guruhlagan sonlarimizni nechtaligi ni chiqarib oldik

pop2021
(0, 1000]            72
(1000, 10000]        68
(10000, 30000]       44
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [ ]:
tr['guruh'] = guruh
tr.head()
# guruh nomli ustunni qoshib oldik

            pop2021  area          guruh
country
Macau       658.394    30      (0, 1000]
Monaco       39.511     2      (0, 1000]
Singapore  5896.686   710  (1000, 10000]
Hong Kong  7552.810  1104  (1000, 10000]
Gibraltar    33.698     6      (0, 1000]

In [ ]:
lk = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data.csv', index_col=0)
lk.sample(7)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970.0
49,mitsubishi,hatchback,93.7,157.3,ohc,four,68,37,5389.0
63,porsche,hatchback,98.4,175.7,dohcv,eight,288,17,NaN
53,nissan,sedan,94.5,165.3,ohc,four,55,45,7099.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
56,nissan,wagon,94.5,170.2,ohc,four,69,31,7349.0

In [ ]:
lk.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [ ]:
binss = [0, 10000, 20000, 50000]

In [ ]:
range = pd.cut(lk.price, binss)
range #price narhiga binss ni boglab qodik sonlar oriligini korsatish uchun

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [ ]:
range.value_counts()

price
(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: count, dtype: int64

In [ ]:
names = ['arzon', "o'rta", 'qimmat']
range = pd.cut(lk.price, binss, labels=names)
range.value_counts()

price
arzon     28
o'rta     17
qimmat    13
Name: count, dtype: int64

.groupby()

In [ ]:
ot = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data.csv', index_col=0)
ot.tail() # dataframeni chaqirib oldik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
ot.company.value_counts() #compan ni lugatlarini chaqirib oldik

company
toyota           7
bmw              6
mazda            5
nissan           5
mercedes-benz    4
audi             4
volkswagen       4
mitsubishi       4
chevrolet        3
jaguar           3
isuzu            3
honda            3
porsche          3
alfa-romero      3
dodge            2
volvo            2
Name: count, dtype: int64

In [ ]:
ot.groupby('company').price.max() #compani ni eng qimmat narhini bilib oldik

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [ ]:
ot.groupby('company').price.mean() # compan ni ortancha narhini bilib oldik

company
alfa-romero      15498.333333
audi             16392.500000
bmw              27213.333333
chevrolet         6007.000000
dodge             6303.000000
honda            10195.000000
isuzu             6785.000000
jaguar           34600.000000
mazda             9654.800000
mercedes-benz    35040.000000
mitsubishi        6689.000000
nissan            8289.000000
porsche          35528.000000
toyota            8216.857143
volkswagen        8435.000000
volvo            13177.500000
Name: price, dtype: float64

In [ ]:
ot.groupby(['company', 'body-style']).horsepower.max() #compani va bod stle ni horsepowerni max qimatini aniqlab oldik

company        body-style
alfa-romero    convertible    111
               hatchback      154
audi           sedan          115
               wagon          110
bmw            sedan          182
chevrolet      hatchback       70
               sedan           70
dodge          hatchback       68
honda          sedan          101
               wagon           76
isuzu          sedan           78
jaguar         sedan          262
mazda          hatchback      101
               sedan           72
mercedes-benz  hardtop        184
               sedan          184
               wagon          123
mitsubishi     hatchback       68
               sedan           88
nissan         sedan          152
               wagon           69
porsche        convertible    207
               hardtop        207
               hatchback      288
toyota         hatchback       62
               wagon          156
volkswagen     sedan          100
volvo          sedan          114
               wagon          114
Name: horsepower, dtype: int64