<a href="https://colab.research.google.com/github/shoxruxmamitov/fayllar-va-malumotlar-ombor/blob/main/iyerarxik_indeks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd #pandas kutubxonasini chaqirib oldik

In [2]:
import numpy as np # np kutubxonasini chaqirib oldik

In [3]:
data = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 3, 2, 1, 3, 1, 2]])
# series hosil qilb oldik va tahmini sonla bn 9 ta qimat va indexlari sonlari uning qismalri a, b, c, d

In [4]:
data #jadvalimizni chaqirib oldik

a  1   -0.445631
   2   -1.536362
   3   -0.736144
b  3   -1.174119
   2    0.158963
c  1   -1.190052
   3   -2.340993
d  1    0.368896
   2   -0.624076
dtype: float64

In [5]:
data['a'] # a indexni chaqirib oldik

1   -0.445631
2   -1.536362
3   -0.736144
dtype: float64

In [6]:
data['b':'d'] # b va d oraligida indexni haqirib oldik

b  3   -1.174119
   2    0.158963
c  1   -1.190052
   3   -2.340993
d  1    0.368896
   2   -0.624076
dtype: float64

In [7]:
data.loc[:, 2]

a   -1.536362
b    0.158963
d   -0.624076
dtype: float64

In [8]:
data[['a','c', 'd']] # a, c, d indexlarni chaqirib oldik

a  1   -0.445631
   2   -1.536362
   3   -0.736144
c  1   -1.190052
   3   -2.340993
d  1    0.368896
   2   -0.624076
dtype: float64

unstack

In [9]:
data

a  1   -0.445631
   2   -1.536362
   3   -0.736144
b  3   -1.174119
   2    0.158963
c  1   -1.190052
   3   -2.340993
d  1    0.368896
   2   -0.624076
dtype: float64

In [10]:
data.unstack() #unstack funksiasi iyerarxik jadvalimizni dataframe korinishiga keltiradi

          1         2         3
a -0.445631 -1.536362 -0.736144
b       NaN  0.158963 -1.174119
c -1.190052       NaN -2.340993
d  0.368896 -0.624076       NaN

stack

In [11]:
data.unstack().stack() #dataframe jadvalini iyerarxik korinishiga keltiradi

a  1   -0.445631
   2   -1.536362
   3   -0.736144
b  2    0.158963
   3   -1.174119
c  1   -1.190052
   3   -2.340993
d  1    0.368896
   2   -0.624076
dtype: float64

dunyo shaharlarining havo va suv sifati malumotlar ustida amallar bajarish

In [12]:
!git clone https://github.com/MansurCompAI/Practicum_Datasets.git #githubdan Practikum datasets ni uklab olamiz

Cloning into 'Practicum_Datasets'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 60 (delta 17), reused 16 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (60/60), 20.24 MiB | 8.61 MiB/s, done.
Resolving deltas: 100% (17/17), done.
Updating files: 100% (13/13), done.

In [13]:
df = pd.read_csv('/content/Practicum_Datasets/world_cities_air_water_quality.csv')
df.head() #praktikum datasets ichidan ozimizga kk li bolan failni chaqirib olamiz

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435

In [14]:
df.info() # dataframe haqida malumotlarni koramiz

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3963 entries, 0 to 3962
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               3963 non-null   object
 1    "Region"          3963 non-null   object
 2    "Country"         3963 non-null   object
 3    "AirQuality"      3963 non-null   float64
 4    "WaterPollution"  3963 non-null   float64
dtypes: float64(2), object(3)
memory usage: 154.9+ KB

In [15]:
columns = ['City', 'Region', 'Country', 'AirQuality', 'WaterPollution']
df.columns = columns
df.head()
#bizda columnlari qoshitirnoq ichida bolganligi uchun biz uni qoshtirnoqsiz qilib qodik sababi bizga muammo iolib kelishi mumkun va
#dataframeda hunuk korinadi

,City,Region,Country,AirQuality,WaterPollution
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435

In [16]:
df['Region'] = df['Region'].map(lambda x:x.replace('"', ''))
df
#biz region columining qimatida qoshtirnoqlarni olib tashladik

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,"""United States of America""",46.816038,49.504950
1,"Washington, D.C.",District of Columbia,"""United States of America""",66.129032,49.107143
2,San Francisco,California,"""United States of America""",60.514019,43.000000
3,Berlin,,"""Germany""",62.364130,28.612717
4,Los Angeles,California,"""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,"""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,Andalusia,"""Spain""",85.714286,8.333333
3960,Vic,Catalonia,"""Spain""",100.000000,0.000000
3961,Segovia,Castile and Leon,"""Spain""",100.000000,0.000000
3962,Zamora city,Castile and Leon,"""Spain""",100.000000,50.000000

In [17]:
df['Country'] = df['Country'].map(lambda x:x.replace('"', ''))
df
# bu safar regio coumining qimatlardagi qoshtinoqlarni olib tashladik

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [18]:
df.to_csv('world_cities_air_water_quality.csv', index=False)
# biz bu dataframeni saqlab oldik

In [19]:
df[df['Country']=='Uzbekistan']
# Country ustunidan Uzbekistonga tegishli bolgan malumotlarni chaqirib oldik ln hech narsa chiqmadi
# sababi ' Uzbekiston' lugatida qoshtirnogida joy tashlab ketilgan bu ham bniza noqulaylik keltiradi

Empty DataFrame
Columns: [City, Region, Country, AirQuality, WaterPollution]
Index: []

In [20]:
df['Country'] = df['Country'].map(lambda x:x.strip())
# biz bu muamoni tugirlab oldik lambda va strip orqali v.h

In [21]:
df['Country'][3] # tugirlanga tugirlanmaganini tekshirib oldik

'Germany'

In [22]:
df[df['Country'] == 'Germany'] # coutrga tegishli bolgan davlatni chaqirib oldik

,City,Region,Country,AirQuality,WaterPollution
3,Berlin,,Germany,62.364130,28.612717
28,Cologne,North Rhine-Westphalia,Germany,60.714286,27.777778
40,Bonn,North Rhine-Westphalia,Germany,82.812500,22.500000
52,Heilbronn,Baden-Wurttemberg,Germany,80.000000,0.000000
76,Aachen,North Rhine-Westphalia,Germany,70.454545,17.857143
...,...,...,...,...,...
2693,Bad Waldsee,Baden-Wurttemberg,Germany,100.000000,50.000000
2714,Weilheim in Oberbayern,Bavaria,Germany,100.000000,50.000000
2727,Buckow,Brandenburg,Germany,87.500000,50.000000
3942,Erfurt,Thuringia,Germany,85.000000,50.000000
3943,Garmisch-Partenkirchen,Bavaria,Germany,100.000000,50.000000

In [23]:
df[df['Country'] == 'Spain'] # countrga tegishli bolgan spain davalatni chaqirib oldik

             City                Region Country  AirQuality  WaterPollution
116     Barcelona             Catalonia   Spain   35.497238       51.315789
240        Madrid   Community of Madrid   Spain   36.234177       18.954248
443        Toledo     Castile-La Mancha   Spain   75.000000       50.000000
489        Girona             Catalonia   Spain  100.000000        0.000000
505    Valladolid      Castile and Leon   Spain   70.000000       41.666667
...           ...                   ...     ...         ...             ...
3956     Palencia      Castile and Leon   Spain   79.166667       37.500000
3959      Cordoba             Andalusia   Spain   85.714286        8.333333
3960          Vic             Catalonia   Spain  100.000000        0.000000
3961      Segovia      Castile and Leon   Spain  100.000000        0.000000
3962  Zamora city      Castile and Leon   Spain  100.000000       50.000000

[78 rows x 5 columns]

In [24]:
df.to_csv('updated_dataset.csv', index=False)
# dataframeni saqlab oldik

pivot table

In [25]:
df.tail() # df ni oxirgi 5 talikni haqirib oldik

             City             Region       Country  AirQuality  WaterPollution
3958        Yanbu    Medina Province  Saudi Arabia    0.000000       50.000000
3959      Cordoba          Andalusia         Spain   85.714286        8.333333
3960          Vic          Catalonia         Spain  100.000000        0.000000
3961      Segovia   Castile and Leon         Spain  100.000000        0.000000
3962  Zamora city   Castile and Leon         Spain  100.000000       50.000000

In [26]:
df1 = pd.pivot_table(df, index=['Country', 'City'], values=['AirQuality', 'WaterPollution'])
df1 #dataframeni iyerarxik indeks qilib oldik va ozimizga kk bolgan ustunlarni tanlab oldik

                      AirQuality  WaterPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000
            Farah     100.000000        0.000000
            Herat      43.750000       31.250000
            Kabul      18.421053       81.060606
            Kandahar    0.000000       75.000000
...                          ...             ...
Zambia      Mansa      75.000000       25.000000
Zimbabwe    Bindura    50.000000       75.000000
            Bulawayo   67.857143       71.428571
            Harare     38.461538       87.500000
            Masvingo   25.000000       62.500000

[3895 rows x 2 columns]

In [27]:
df1.index # indexlarni chaqirib oldik

MultiIndex([('Afghanistan',        'Andkhoy'),
            ('Afghanistan',          'Farah'),
            ('Afghanistan',          'Herat'),
            ('Afghanistan',          'Kabul'),
            ('Afghanistan',       'Kandahar'),
            ('Afghanistan', 'Mazar-i-Sharif'),
            (    'Albania',         'Ballsh'),
            (    'Albania',         'Burrel'),
            (    'Albania',         'Durres'),
            (    'Albania',        'Elbasan'),
            ...
            (      'Yemen',          'Sanaa'),
            (      'Yemen',         'Ta'izz'),
            (     'Zambia',       'Chingola'),
            (     'Zambia',          'Kitwe'),
            (     'Zambia',         'Lusaka'),
            (     'Zambia',          'Mansa'),
            (   'Zimbabwe',        'Bindura'),
            (   'Zimbabwe',       'Bulawayo'),
            (   'Zimbabwe',         'Harare'),
            (   'Zimbabwe',       'Masvingo')],
           names=['Country', 'City'], length=3895)

In [28]:
df1.loc['Uzbekistan'] #.loc qilib uzbeksitonga tegishli bolgan malumotlarni chaqirib oldk

          AirQuality  WaterPollution
City
Tashkent   56.451613       49.166667

In [29]:
df1.loc[['Uzbekistan', 'Albania']] #bunda ham huddi shunaqa uzb va albania ga tegishli malumotlni chaqirib oldik

                     AirQuality  WaterPollution
Country    City
Uzbekistan Tashkent   56.451613       49.166667
Albania    Ballsh      0.000000       62.500000
           Burrel    100.000000       62.500000
           Durres     37.500000       62.500000
           Elbasan     0.000000       25.000000
           Kamez      50.000000      100.000000
           Kavaje    100.000000       75.000000
           Korce      75.000000       25.000000
           Lushnje     0.000000      100.000000
           Permet    100.000000        0.000000
           Shkoder    75.000000       33.333333
           Tirana     18.316832       73.177083
           Vlore      66.666667       75.000000

In [30]:
df1.sort_values('Country', ascending=False)
#

                            AirQuality  WaterPollution
Country     City
Zimbabwe    Masvingo         25.000000       62.500000
            Harare           38.461538       87.500000
            Bulawayo         67.857143       71.428571
            Bindura          50.000000       75.000000
Zambia      Mansa            75.000000       25.000000
...                                ...             ...
Afghanistan Herat            43.750000       31.250000
            Farah           100.000000        0.000000
            Kandahar          0.000000       75.000000
            Mazar-i-Sharif   11.111111       83.333333
            Andkhoy          50.000000       50.000000

[3895 rows x 2 columns]

iyerarxik malumotlar ustuni

In [34]:
df2 = df1.copy()
df2.sample(7)
# df1 datframeni df2 ga copi qilib kochirib oldik va 5 ta qatorni chaqirib oldik

                                        AirQuality  WaterPollution
Country                    City
Indonesia                  Manado        50.000000       58.333333
Pakistan                   Peshawar      29.054054       55.468750
People's Republic of China Baoding       35.714286       33.333333
India                      Jalgaon       33.750000       54.687500
United States of America   La Crosse    100.000000       50.000000
Pakistan                   Sheikhupura   50.000000      100.000000
Greece                     Zakynthos    100.000000       25.000000

In [35]:
df2['AirPollution'] = 100-df2['AirQuality']
df2 #airquality ustuniga teskari bilgan yangi ustun hosil qildik

                      AirQuality  WaterPollution  AirPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000     50.000000
            Farah     100.000000        0.000000      0.000000
            Herat      43.750000       31.250000     56.250000
            Kabul      18.421053       81.060606     81.578947
            Kandahar    0.000000       75.000000    100.000000
...                          ...             ...           ...
Zambia      Mansa      75.000000       25.000000     25.000000
Zimbabwe    Bindura    50.000000       75.000000     50.000000
            Bulawayo   67.857143       71.428571     32.142857
            Harare     38.461538       87.500000     61.538462
            Masvingo   25.000000       62.500000     75.000000

[3895 rows x 3 columns]

In [36]:
df2['WaterQuality'] = 100-df2['WaterPollution']
df2 #waterpollution ga teskari bolgan waterqualt ustunini hosil qilib oldik

                      AirQuality  WaterPollution  AirPollution  WaterQuality
Country     City
Afghanistan Andkhoy    50.000000       50.000000     50.000000     50.000000
            Farah     100.000000        0.000000      0.000000    100.000000
            Herat      43.750000       31.250000     56.250000     68.750000
            Kabul      18.421053       81.060606     81.578947     18.939394
            Kandahar    0.000000       75.000000    100.000000     25.000000
...                          ...             ...           ...           ...
Zambia      Mansa      75.000000       25.000000     25.000000     75.000000
Zimbabwe    Bindura    50.000000       75.000000     50.000000     25.000000
            Bulawayo   67.857143       71.428571     32.142857     28.571429
            Harare     38.461538       87.500000     61.538462     12.500000
            Masvingo   25.000000       62.500000     75.000000     37.500000

[3895 rows x 4 columns]

In [39]:
df3 = pd.DataFrame(df2.values, index=df2.index, columns=[['AIR', 'AIR', 'WATER', 'WATER'], ['AirQuality', 'AirPollution',	'WaterPollution', 'WaterQuality']])
df3

                             AIR                       WATER
                      AirQuality AirPollution WaterPollution WaterQuality
Country     City
Afghanistan Andkhoy    50.000000    50.000000      50.000000    50.000000
            Farah     100.000000     0.000000       0.000000   100.000000
            Herat      43.750000    31.250000      56.250000    68.750000
            Kabul      18.421053    81.060606      81.578947    18.939394
            Kandahar    0.000000    75.000000     100.000000    25.000000
...                          ...          ...            ...          ...
Zambia      Mansa      75.000000    25.000000      25.000000    75.000000
Zimbabwe    Bindura    50.000000    75.000000      50.000000    25.000000
            Bulawayo   67.857143    71.428571      32.142857    28.571429
            Harare     38.461538    87.500000      61.538462    12.500000
            Masvingo   25.000000    62.500000      75.000000    37.500000

[3895 rows x 4 columns]

In [40]:
df3['AIR'] #air ustunini chaqirib oldik

                      AirQuality  AirPollution
Country     City
Afghanistan Andkhoy    50.000000     50.000000
            Farah     100.000000      0.000000
            Herat      43.750000     31.250000
            Kabul      18.421053     81.060606
            Kandahar    0.000000     75.000000
...                          ...           ...
Zambia      Mansa      75.000000     25.000000
Zimbabwe    Bindura    50.000000     75.000000
            Bulawayo   67.857143     71.428571
            Harare     38.461538     87.500000
            Masvingo   25.000000     62.500000

[3895 rows x 2 columns]

In [41]:
df3['WATER']# WATER ga tegishli bolgan ustunni chaqirib oldik

                      WaterPollution  WaterQuality
Country     City
Afghanistan Andkhoy        50.000000     50.000000
            Farah           0.000000    100.000000
            Herat          56.250000     68.750000
            Kabul          81.578947     18.939394
            Kandahar      100.000000     25.000000
...                              ...           ...
Zambia      Mansa          25.000000     75.000000
Zimbabwe    Bindura        50.000000     25.000000
            Bulawayo       32.142857     28.571429
            Harare         61.538462     12.500000
            Masvingo       75.000000     37.500000

[3895 rows x 2 columns]

In [44]:
df3.columns.names = ['Object', 'Info']
df3 # ustunlarnigng oziga ham alohida nom berib oldik

Object                       AIR                       WATER
Info                  AirQuality AirPollution WaterPollution WaterQuality
Country     City
Afghanistan Andkhoy    50.000000    50.000000      50.000000    50.000000
            Farah     100.000000     0.000000       0.000000   100.000000
            Herat      43.750000    31.250000      56.250000    68.750000
            Kabul      18.421053    81.060606      81.578947    18.939394
            Kandahar    0.000000    75.000000     100.000000    25.000000
...                          ...          ...            ...          ...
Zambia      Mansa      75.000000    25.000000      25.000000    75.000000
Zimbabwe    Bindura    50.000000    75.000000      50.000000    25.000000
            Bulawayo   67.857143    71.428571      32.142857    28.571429
            Harare     38.461538    87.500000      61.538462    12.500000
            Masvingo   25.000000    62.500000      75.000000    37.500000

[3895 rows x 4 columns]

In [47]:
#df3.index.names = ['ss', 'ss'] indexni ham nomini ozgartirsak boladi ln bizda hammasi zor

qayta tartiblash

In [49]:
df3

Object                       AIR                       WATER
Info                  AirQuality AirPollution WaterPollution WaterQuality
Country     City
Afghanistan Andkhoy    50.000000    50.000000      50.000000    50.000000
            Farah     100.000000     0.000000       0.000000   100.000000
            Herat      43.750000    31.250000      56.250000    68.750000
            Kabul      18.421053    81.060606      81.578947    18.939394
            Kandahar    0.000000    75.000000     100.000000    25.000000
...                          ...          ...            ...          ...
Zambia      Mansa      75.000000    25.000000      25.000000    75.000000
Zimbabwe    Bindura    50.000000    75.000000      50.000000    25.000000
            Bulawayo   67.857143    71.428571      32.142857    28.571429
            Harare     38.461538    87.500000      61.538462    12.500000
            Masvingo   25.000000    62.500000      75.000000    37.500000

[3895 rows x 4 columns]

In [51]:
df3.swaplevel('Country', 'City')
# swaplevel orqali country va city joylarini almashtirib oldik

Object                       AIR                       WATER
Info                  AirQuality AirPollution WaterPollution WaterQuality
City     Country
Andkhoy  Afghanistan   50.000000    50.000000      50.000000    50.000000
Farah    Afghanistan  100.000000     0.000000       0.000000   100.000000
Herat    Afghanistan   43.750000    31.250000      56.250000    68.750000
Kabul    Afghanistan   18.421053    81.060606      81.578947    18.939394
Kandahar Afghanistan    0.000000    75.000000     100.000000    25.000000
...                          ...          ...            ...          ...
Mansa    Zambia        75.000000    25.000000      25.000000    75.000000
Bindura  Zimbabwe      50.000000    75.000000      50.000000    25.000000
Bulawayo Zimbabwe      67.857143    71.428571      32.142857    28.571429
Harare   Zimbabwe      38.461538    87.500000      61.538462    12.500000
Masvingo Zimbabwe      25.000000    62.500000      75.000000    37.500000

[3895 rows x 4 columns]

In [53]:
df3.sort_index(level=0, ascending=False)
#df3 qimatlarini teskaei tartibda tahlab oldik

Object                       AIR                       WATER
Info                  AirQuality AirPollution WaterPollution WaterQuality
Country     City
Zimbabwe    Masvingo   25.000000    62.500000      75.000000    37.500000
            Harare     38.461538    87.500000      61.538462    12.500000
            Bulawayo   67.857143    71.428571      32.142857    28.571429
            Bindura    50.000000    75.000000      50.000000    25.000000
Zambia      Mansa      75.000000    25.000000      25.000000    75.000000
...                          ...          ...            ...          ...
Afghanistan Kandahar    0.000000    75.000000     100.000000    25.000000
            Kabul      18.421053    81.060606      81.578947    18.939394
            Herat      43.750000    31.250000      56.250000    68.750000
            Farah     100.000000     0.000000       0.000000   100.000000
            Andkhoy    50.000000    50.000000      50.000000    50.000000

[3895 rows x 4 columns]