<a href="https://colab.research.google.com/github/shoxruxmamitov/fayllar-va-malumotlar-ombor/blob/main/malumotlarni_tayyorlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # pandas  ni chaqirib oldik

In [ ]:
import numpy as np # np ni chaqirib oldik

dropna funksiasi

In [ ]:
st = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv', index_col=0)
st # githubdan jadvalni dataframe qilib chaqirib oldik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
st.isnull() # mavjud bolmagan qimatlarni chaqirib oldik mavjud bolmagan qimatlarni True qilib belgilidi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,False,False,False,False,False,False,True,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...
81,False,False,False,False,False,False,False,False,False
82,False,False,True,False,True,False,False,False,False
86,False,False,False,True,False,False,False,True,False
87,False,False,False,False,True,False,False,False,False
88,False,False,False,False,False,False,True,False,False

In [ ]:
st.notnull() # notnull ham mavjud bolmagan qimatlarni chaqiradi va False qilib bwlgilidi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,True,True,True,True,True,True,False,True,True
1,True,True,False,True,True,True,True,True,True
2,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...
81,True,True,True,True,True,True,True,True,True
82,True,True,False,True,False,True,True,True,True
86,True,True,True,False,True,True,True,False,True
87,True,True,True,True,False,True,True,True,True
88,True,True,True,True,True,True,False,True,True

In [ ]:
st.isnull().sum() # qasi qatorda mavjud bolmagan qimatlarni sonini chiaqrib berdi

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [ ]:
len(st) # uzunligni hisoblab oldik

61

In [ ]:
st.isnull().sum()/len(st)*100 # mavjud bolmagan qimatlarni sonini chaqirib proporsiasini hisoblab va uning foizini 100 ga kopatirib bilib oldik

index                0.000000
company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [ ]:
st.dropna() # mavjud bolmagan qimatlarni ochrib oldik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [ ]:
len(st.dropna()) # ochirib olgan qimatlarni sonini bilib oldik

14

In [ ]:
st.dropna(axis=1) #mavjud bolmagan ustunlarni tashlab oldik

           company   body-style num-of-cylinders
index
0      alfa-romero  convertible             four
1      alfa-romero  convertible             four
2      alfa-romero    hatchback              six
3             audi        sedan             four
4             audi        sedan             five
...            ...          ...              ...
81      volkswagen        sedan             four
82      volkswagen        sedan             four
86      volkswagen        sedan             four
87           volvo        sedan             four
88           volvo        wagon             four

[61 rows x 3 columns]

In [ ]:
st.dropna(axis=1, thresh=48)
# mavjud bolmagan qimatlarni 48 tadan kam bolgan ustunni tashlashnu buirdik

           company   body-style  length engine-type num-of-cylinders    price
index
0      alfa-romero  convertible   168.8        dohc             four  13495.0
1      alfa-romero  convertible   168.8        dohc             four  16500.0
2      alfa-romero    hatchback   171.2        ohcv              six  16500.0
3             audi        sedan   176.6         ohc             four  13950.0
4             audi        sedan   176.6         ohc             five  17450.0
...            ...          ...     ...         ...              ...      ...
81      volkswagen        sedan   171.7         ohc             four   7975.0
82      volkswagen        sedan   171.7         NaN             four   7995.0
86      volkswagen        sedan     NaN         ohc             four   9995.0
87           volvo        sedan   188.8         NaN             four  12940.0
88           volvo        wagon   188.8         ohc             four  13415.0

[61 rows x 6 columns]

In [ ]:
st.dropna(subset=['price'])
# price ustnini nan bolgan qimatlarni subset orqali ochirishni buirdik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
9,bmw,sedan,101.2,NaN,ohc,four,NaN,23.0,16430.0
10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0
11,bmw,sedan,101.2,176.8,ohc,six,121.0,NaN,20970.0
13,bmw,sedan,103.5,189.0,ohc,six,NaN,16.0,30760.0
14,bmw,sedan,103.5,NaN,ohc,six,182.0,16.0,41315.0
15,bmw,sedan,110.0,197.0,ohc,six,182.0,NaN,36880.0
16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
18,chevrolet,sedan,NaN,158.8,ohc,four,70.0,NaN,6575.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
27,honda,wagon,96.5,NaN,ohc,four,76.0,30.0,7295.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
29,honda,sedan,NaN,169.1,ohc,four,NaN,25.0,10345.0
30,isuzu,sedan,NaN,170.7,ohc,four,78.0,24.0,6785.0
33,jaguar,sedan,113.0,NaN,dohc,six,NaN,15.0,32250.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
35,jaguar,sedan,NaN,191.7,ohcv,twelve,262.0,13.0,36000.0
36,mazda,hatchback,93.1,159.1,NaN,four,NaN,NaN,5195.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
39,mazda,hatchback,NaN,NaN,NaN,two,101.0,17.0,11845.0
43,mazda,sedan,104.9,175.0,ohc,four,NaN,NaN,18344.0
44,mercedes-benz,sedan,110.0,190.9,NaN,five,123.0,22.0,25552.0
45,mercedes-benz,wagon,NaN,190.9,ohc,five,123.0,22.0,28248.0
46,mercedes-benz,sedan,120.9,208.1,NaN,eight,184.0,14.0,40960.0
47,mercedes-benz,hardtop,112.0,199.2,NaN,eight,184.0,14.0,45400.0
49,mitsubishi,hatchback,NaN,157.3,ohc,four,NaN,37.0,5389.0
50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
51,mitsubishi,sedan,96.3,172.4,NaN,four,88.0,NaN,6989.0
52,mitsubishi,sedan,96.3,172.4,ohc,four,NaN,25.0,8189.0
53,nissan,sedan,NaN,NaN,ohc,four,55.0,NaN,7099.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
55,nissan,sedan,NaN,165.3,ohc,four,69.0,31.0,6849.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
57,nissan,sedan,100.4,184.6,ohcv,six,152.0,NaN,13499.0
61,porsche,hardtop,NaN,NaN,NaN,six,207.0,17.0,34028.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0
80,volkswagen,sedan,97.3,NaN,ohc,four,NaN,37.0,7775.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

.fillna() funksiasi

In [ ]:
st.sample(10)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0
45,mercedes-benz,wagon,NaN,190.9,ohc,five,123.0,22.0,28248.0
33,jaguar,sedan,113.0,NaN,dohc,six,NaN,15.0,32250.0
63,porsche,hatchback,98.4,175.7,dohcv,eight,NaN,NaN,NaN
16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
9,bmw,sedan,101.2,NaN,ohc,four,NaN,23.0,16430.0

In [ ]:
st.fillna(99)
# fillna orqali mavjud bolmagan qimatlarga 99 qimat berib oldik ln bu ozgincha xato

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,99.0,21.0,13495.0
1,alfa-romero,convertible,99.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,99.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,99.0,99.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,99.0,171.7,99,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,99.0,ohc,four,100.0,99.0,9995.0
87,volvo,sedan,104.3,188.8,99,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,99.0,23.0,13415.0

In [ ]:
st.fillna({'horsepower':87, 'whell-base':92})
#fillna orqali ozimiz hoxlagan ustunga qimat berib chiqdik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,87.0,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,87.0,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,87.0,23.0,13415.0

In [ ]:
st.fillna({'average-mileage':np.mean(st['average-mileage']), 'horsepower':np.mean(st['horsepower'])})
#average-mileage va horsepower qimatlariga ortancha qimatni berib oldik np.mean orqali

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,108.266667,21.000000,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.000000,21.000000,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.000000,25.695652,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.000000,24.000000,13950.0
4,audi,sedan,99.4,176.6,ohc,five,108.266667,25.695652,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.000000,27.000000,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.000000,37.000000,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.000000,25.695652,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.000000,23.000000,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,108.266667,23.000000,13415.0

In [ ]:
st.fillna(method='ffill')
#ffill funksiasi orqali mavjud bolmagan qimatni ozidan bitta tepada bolgan qimatni oziga kochirib oladi

/tmp/ipykernel_400/1690288892.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  st.fillna(method='ffill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [ ]:
st.fillna(method='bfill')
# bfill funksiasi orqali mavjud bolmagan qimat ozidan bitta past bolgan qimatdan oziga kochirib oladi

/tmp/ipykernel_400/463688767.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  st.fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
st[st.company=='toyota'].fillna(method='bfill')
# company ustunidan toyota qimatiga bfill funksiasini berib oldik va qimat berdik

/tmp/ipykernel_400/384019631.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  st[st.company=='toyota'].fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0