<a href="https://colab.research.google.com/github/shoxruxmamitov/fayllar-va-malumotlar-ombor/blob/main/malumotlar_toplamini_uygunlashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd # pandas ni chaqirib oldik

In [2]:
import numpy as np # nump ni chaqirib olVik

In [ ]:
!git clone https://github.com/MansurCompAI/Practicum_Datasets.git #githubdan dataset faillarini chaiqirib oldik

Cloning into 'Practicum_Datasets'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 60 (delta 17), reused 16 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (60/60), 20.24 MiB | 12.75 MiB/s, done.
Resolving deltas: 100% (17/17), done.

In [ ]:
movies = pd.read_csv('/content/Practicum_Datasets/IMDb/IMDb_movies.csv')
movies.head() # 1 chi datasetsni chaqirib oldik

/tmp/ipykernel_453/731770191.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv('/content/Practicum_Datasets/IMDb/IMDb_movies.csv')

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN

In [ ]:
movies.info() # dataset haqida malumotlarni chaqirib oldik

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85855 entries, 0 to 85854
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   imdb_title_id       85855 non-null  object
 1   title               85855 non-null  object
 2   original_title      85855 non-null  object
 3   year                85855 non-null  object
 4   date_published      85855 non-null  object
 5   genre               85855 non-null  object
 6   duration            85855 non-null  int64
 7   country             85791 non-null  object
 8   language            84954 non-null  object
 9   director            85768 non-null  object
 10  writer              84283 non-null  object
 11  production_company  81400 non-null  object
 12  actors              85786 non-null  object
 13  description         83740 non-null  object
 14  budget              23710 non-null  object
dtypes: int64(1), object(14)
memory usage: 9.8+ MB

In [ ]:
ratings = pd.read_csv('/content/Practicum_Datasets/IMDb/IMDb_ratings.csv')
ratings  # 2 chi datasetni chaqirib oldik

      imdb_title_id  weighted_average_vote  total_votes
0         tt0000009                    5.9          154
1         tt0000574                    6.1          589
2         tt0001892                    5.8          188
3         tt0002101                    5.2          446
4         tt0002130                    7.0         2237
...             ...                    ...          ...
85850     tt9908390                    5.3          398
85851     tt9911196                    7.7          724
85852     tt9911774                    7.9          265
85853     tt9914286                    6.4          194
85854     tt9914942                    6.7          102

[85855 rows x 3 columns]

In [ ]:
ratings.info() #datasets haqida malumotlarni bilib oldik

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85855 entries, 0 to 85854
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   imdb_title_id          85855 non-null  object
 1   weighted_average_vote  85855 non-null  float64
 2   total_votes            85855 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.0+ MB

Merging

In [ ]:
movies_ratings = pd.merge(movies, ratings)
movies_ratings.head()
# ikta dataframeni uygunlashtirib oldik

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget,weighted_average_vote,total_votes
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN,5.9,154
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250,6.1,589
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN,5.8,188
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000,5.2,446
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN,7.0,2237

In [ ]:
extratect = movies_ratings[['title', 'year', 'weighted_average_vote', 'total_votes']]
extratect.head(10) # endi ustunlarni tozalab oldik bir xil ustun va buzga kk emas ustunlarni chiqarib tashladik va buzga kk bolgan ustunni qoldirdik

,title,year,weighted_average_vote,total_votes
0,Miss Jerry,1894,5.9,154
1,The Story of the Kelly Gang,1906,6.1,589
2,Den sorte drøm,1911,5.8,188
3,Cleopatra,1912,5.2,446
4,L'Inferno,1911,7.0,2237
5,"From the Manger to the Cross; or, Jesus of Naz...",1912,5.7,484
6,Madame DuBarry,1919,6.8,753
7,Quo Vadis?,1913,6.2,273
8,Independenta Romaniei,1912,6.7,198
9,Richard III,1912,5.5,225

sodda misollar

In [36]:
A = pd.DataFrame({'Transport': ['poezd', 'avtomobil', 'kema'],
                  'Tezligi': ['70', '185', '65']})
A # dataframe hosil qilib olamiz

   Transport Tezligi
0      poezd      70
1  avtomobil     185
2       kema      65

In [8]:
B = pd.DataFrame({'Transport': ['poezd', 'avtomobil', 'tramvay'],
                  'Narhi':['98000', '110000', '132000']})
B # ikkinchi dataframe hpsil qilib oldik bunda 2 la df da Transport ustuni bir hil

   Transport   Narhi
0      poezd   98000
1  avtomobil  110000
2    tramvay  132000

merge funksiasi

In [37]:
merged = pd.merge(A, B)
merged # ikkla adataframeni merge funksiasi orqali qoshib oldik va bunda bizaga tezlik va narh bitta dataframeda boldi ln tramvay va kema qoshilmadi
# bu funksia INNER JOIN (ichki qoshilish) deb ataladi

   Transport Tezligi   Narhi
0      poezd      70   98000
1  avtomobil     185  110000

In [38]:
merged = pd.merge(A, B, how='outer')
merged # bu funksia da 2 ta dataframeda mavjud bolgan va mavjud bolmagan dataframe qimatlari qoshilavi qoshilganda bir qimat b9lmassa nan qimat beradi
 # bu bizada OUTER JOIN (tashqi qoshilish) deb ataladi

   Transport Tezligi   Narhi
0  avtomobil     185  110000
1       kema      65     NaN
2      poezd      70   98000
3    tramvay     NaN  132000

In [39]:
merged_lift = pd.merge(A, B, how='left') # how = 'left' (chap tomon qoshilish) deb ataladi
merged_lift # bu funksia 2 la dataframedan ustunlarni olib ln (how=left) qilganligimiz uchun faqat A datafrmedan hamma indexlarni oldi
            # ln B dataframedan 2 la dataframe bir xil bolmagan qimatlarni olmaydi
# how = 'left' funksiasi bizga faqat ongdagi dataframeni ustunlarini 100 foiz qilib chiqarib beradi

   Transport Tezligi   Narhi
0      poezd      70   98000
1  avtomobil     185  110000
2       kema      65     NaN

In [40]:
merged_right = pd.merge(A, B, how='right') # how = 'right' (ong tomon qoshilish) deb t=ataladi
merged_right #  # bu funksia 2 la dataframedan ustunlarni olib ln (how=right) qilganligimiz uchun faqat B datafrmedan hamma indexlarni oldi
            # ln A dataframedan 2 la dataframe bir xil bolmagan qimatlarni olmaydi
# how = 'right' funksiasi bizga faqat chapdagi dataframeni ustunlarini 100 foiz qilib chiqarib beradi

   Transport Tezligi   Narhi
0      poezd      70   98000
1  avtomobil     185  110000
2    tramvay     NaN  132000

df

In [42]:
R = pd.DataFrame({'Transport': ['Avtomobil', 'Kema', 'Belaz'],
                  "Tezligi": ['220', '230', '150']})
R # dataframe hosil qilib oldik

   Transport Tezligi
0  Avtomobil     220
1       Kema     230
2      Belaz     150

In [43]:
S = pd.DataFrame({'Transport_turi': ['Avtomobil', 'Kema', 'Tank'],
                  "Og'irligi": ['23', '178', '78']})
S #dataframe hosil qilib oldik

  Transport_turi Og'irligi
0      Avtomobil        23
1           Kema       178
2           Tank        78

In [45]:
merg = pd.merge(R, S, left_on='Transport', right_on='Transport_turi')
merg # bu funksia orqali ikkala dataframeni qoshib oldik left va right tomondan ham ustunlarni qoshib oldik

   Transport Tezligi Transport_turi Og'irligi
0  Avtomobil     220      Avtomobil        23
1       Kema     230           Kema       178

In [48]:
merg1 = merg[['Transport', 'Tezligi', "Og'irligi"]]
merg1 # merg dan ozimizga kk bolgan ustunlarni qoldirdik

   Transport Tezligi Og'irligi
0  Avtomobil     220        23
1       Kema     230       178

agar bizda indekslar har xil bolsa

In [52]:
merged1 = pd.merge(S, R, left_index=True, right_on='Transport')
merged1 # bu funksiya da S da indeximiz bolmagan ligimi sababli left_index=True qildik

  Og'irligi  Transport Tezligi
0        23  Avtomobil     220
1       178       Kema     230