<a href="https://colab.research.google.com/github/shoxruxmamitov/fayllar-va-malumotlar-ombor/blob/main/qimatlarni_ozgartirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # pandas ni chaqirib oldik

In [ ]:
import numpy as np # np ni chaqirib oldik

takrori qimatlarni ochirish

In [ ]:
tf = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population_duplicates.csv')
# githubdan dataframeni chaqirib oldik

In [ ]:
tf.tail()
# tf dataframedan ohirgi 5 qatorni chiqarib oldik

     rank           country  density  densityMi   pop2021     area
242   228           Namibia   3.1338     8.1166  2587.344   825615
243   229    Western Sahara   2.3003     5.9577   611.875   266000
244   230          Mongolia   2.1286     5.5129  3329.289  1564110
245   231  Falkland Islands   0.2902     0.7517     3.533    12173
246   232         Greenland   0.0263     0.0680    56.877  2166086

In [ ]:
tf.duplicated()
# takrorlangan qimatlar mavjud mavjud emasligini bilib oldik

0      False
1      False
2      False
3       True
4       True
       ...
242    False
243    False
244    False
245    False
246    False
Length: 247, dtype: bool

In [ ]:
tf.shape
# dataframeni qatorlarini aniqlab oldik

(247, 6)

In [ ]:
tf.duplicated().sum()

np.int64(15)

In [ ]:
tf.drop_duplicates()
# takrori qimatlarni olib tashladik

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

In [ ]:
tf.drop_duplicates(['country'])
# shu ustunni bir xil bolgan qimatlarni olib tashladik

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

map() qimatlani moslash

In [ ]:
kl = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv', index_col=0)
kl.head()
# githubdan jadval chaqirib olib uni dataframe korinishiga otkizib oldik va boshidan 5  qatorni chiqarib ham oldik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
kl['num-of-cylinders'].unique()
# num-of qimatlarni chiqarib oldik

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [ ]:
dict = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}
dict # va dict orqali str qimatlarni int korinishiga otqizish uchun list korinishiga keltirib oldik

{'two': 2,
 'three': 3,
 'four': 4,
 'five': 5,
 'six': 6,
 'eight': 8,
 'twelve': 12}

In [ ]:
kl['cylinders'] = kl['num-of-cylinders'].map(dict)
kl # va cylinders nomli yangi ustun berdik va num-of-cylinders gsa ulab .map(dict) qilib int larni kirgizib oldik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4

In [ ]:
kl['price']
# price ustunini chaqirib oldik

index
0     13495.0
1     16500.0
2     16500.0
3     13950.0
4     17450.0
       ...
81     7975.0
82     7995.0
86     9995.0
87    12940.0
88    13415.0
Name: price, Length: 61, dtype: float64

In [ ]:
narh = 12080
kl['prcie_uzb'] = kl['price'].map(lambda x:  x*100)
kl # yangi price_uzb ustun yaratib oldik va map orqali lambda x:  x*100 shu funksiani berib oldik

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,prcie_uzb
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,1349500.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,1650000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,1650000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,1395000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,1745000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,797500.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,799500.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,999500.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,1294000.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,1341500.0

.replace() .rename() funksialri

In [ ]:
kl.replace(dict)
# .replace orqali istalgan ustunni qimatlarini ozgartirishimiz mumkun

/tmp/ipykernel_292/2280454424.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  kl.replace(dict)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,prcie_uzb
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,1349500.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,1650000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,1650000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,1395000.0
4,audi,sedan,99.4,176.6,ohc,5,NaN,NaN,17450.0,5,1745000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,797500.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,799500.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,999500.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,1294000.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,1341500.0

In [ ]:
tf.head()

   rank  country     density   densityMi    pop2021   area
0     1    Macau  21946.4667  56841.3487    658.394     30
1     2   Monaco  19755.5000  51166.7450     39.511      2
2    28  Burundi    440.3044   1140.3884  12255.433  27834
3     1    Macau  21946.4667  56841.3487    658.394     30
4     2   Monaco  19755.5000  51166.7450     39.511      2

In [ ]:
rt = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population_duplicates.csv', index_col='country')
rt.head() # dataframe qilib oldik va indexni country qildik

         rank     density   densityMi    pop2021   area
country
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2
Burundi    28    440.3044   1140.3884  12255.433  27834
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2

In [ ]:
rt.rename(index=str.upper)
# qatorini katta harf qildik

                  rank     density   densityMi    pop2021     area
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
rt.rename(columns=str.upper)
#ustunini katta harf qilib oldik

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
rt.rename(index=str.upper, columns=str.upper)
# ham ustun ham qatorni katta harf qilib oldik

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
rt.rename(index={'Macau':'Makao'}, columns={'pop2022':'population'}, inplace=True)
# index qatoridagi Macau va columns qatordagi pop2022 nomlarini ozgartirib oldik

In [ ]:
rt

                  rank     density   densityMi    pop2021     area
country
Makao                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Makao                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]